name: settings
description: Automatic persisted structure generation macro.
version: 0.0.1
homepage: https://github.com/deminearchiver/settings
repository: https://github.com/deminearchiver/settings

environment:
  sdk: '>=3.5.0-304.0.dev <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  collection: ^1.18.0
  flutter:
    sdk: flutter
  flutter_secure_storage: any
  macros: ^0.1.2-main.4
  meta: ^1.15.0
  shared_preferences: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter: